import { getUniqStr } from '@components/Form/helpers';

import { CreditFormData, CreditPurpose } from '../../form-cc/types';

export const cashCreditDefaultValues: CreditFormData = {
    // Personal Info
    fullName: '',
    phone: '',
    email: '',
    birthDate: '',
    acception: '1',
    gender: 'M',
    agreement: true,
    phcc: '',
    token: '',
    // Credit Params
    creditAmount: '500000',
    creditPeriod: '60',
    hash: getUniqStr(),
    insurance: true,
    creditTotalAmount: '',
    monthlyPayment: '',
    creditPurpose: CreditPurpose.OTHERS,
    officeRegion: '100000077',
    officeCity: 'Москва',
    officeBranch: '',
    filialCode: '',
    selectedOffice: undefined,

    // Personal Info
    passportSeries: '',
    passportNumber: '',
    passportDivisionCode: '',
    passportIssuer: '',
    passportDate: '',
    birthPlace: '',
    surnameChanged: false,
    previousSurname: '',

    registerFullAddress: '',
    registerRegion: '',
    registerCity: '',
    registerStreet: '',
    registerBuilding: '',
    registerFlat: '',
    registerKorpus: '',
    registerLocality: '',
    registerPostalCode: '',
    registerArea: '',
    registrationAndLivingSame: true,
    livingFullAddress: '',
    livingCity: '',
    livingRegion: '',
    livingLocality: '',
    livingStreet: '',
    livingBuilding: '',
    livingKorpus: '',
    livingFlat: '',
    livingPostalCode: '',
    livingArea: '',

    // Income Info
    occupation: '',
    incomeSource: '',
    incomeAmount: '',
    maritalStatus: '',
    extraIncome: false,
    extraIncomeSource: '',
    extraIncomeAmount: '',
    companyName: '',
    inn: '',
    companyType: '',
    employeeAmount: '',
    position: '',
    employmentStartDate: '',
    companyPhonenumber: '',
    companyPhoneAdditions: '',
    companyAddress: '',
    companyRegion: '',
    companyCity: '',
    companyLocality: '',
    companyStreet: '',
    companyBuilding: '',
    companyKorpus: '',
    companyPostalCode: '',
};
